### ISSUE TITLE
Implement MongoClient class

### ISSUE THREAD

**Issue by alcaeus** [alcaeus/mongo-php-adapter#1]
- [ ] Implement methods not yet implemented
- [ ] Provide `__get` for properties such as `$connected`?
- [ ] Ensure handling of read preference (must be passed on to other classes)

**Comment by RageZBla** [comment]
I will take a look at this next.

**Comment by alcaeus** [comment]
Merged in https://github.com/alcaeus/mongo-php-adapter/commit/885f69953076da6616d558b6ba9cc95dcbc706fe. Thanks @RageZBla!
