### ISSUE TITLE
Changed to be the case

### ISSUE THREAD

**Issue by shanghaiyangming** [alcaeus/mongo-php-adapter#103]
`<?php
include "vendor/autoload.php";
$alias = 'ABCDEFG';
try {
	new \MongoId($alias);
	var_dump($alias);
} catch (\MongoException $ex) {
	var_dump($alias);//"abcdefg"
}`

**Comment by alcaeus** [comment]
Thanks for the report. This is an issue in the new MongoDB driver which will be fixed with the upcoming version. See https://github.com/mongodb/mongo-php-driver/pull/297 for more details.

**Comment by shanghaiyangming** [comment]
thank you~~!
