### ISSUE TITLE
Can't query on admin.$cmd.sys.inprog to get currentOp

### ISSUE THREAD

**Issue by Identity-labs** [alcaeus/mongo-php-adapter#110]
Hi, 

With the old MongoClient we can do

    $client = new \MongoClient('mongodb://root:foooBarrrrr@localhost:27017?authSource=admin');
    $collection = $client->selectDb('admin')->selectCollection('$cmd.sys.inprog');
    $currentOp = $collection->findOne();
    $inprog = isset($currentOp['inprog'])?$currentOp['inprog']:array();
    var_dump($inprog);

An other solution to do that ?

The exception throw by MongoPhpAdapter :

======================================================================
   The application has thrown an exception!
======================================================================
 MongoException
 Invalid collection name: admin.$cmd.sys.inprog
----------------------------------------------------------------------
/vendor/alcaeus/mongo-php-adapter/lib/Alcaeus/MongoDbAdapter/ExceptionConverter.php:83
/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php(558): Alcaeus\MongoDbAdapter\ExceptionConverter::toLegacy(Object(MongoDB\Driver\Exception\RuntimeException))
======================================================================
   Previous Exception(s):
======================================================================
 MongoDB\Driver\Exception\RuntimeException
 Invalid collection name: admin.$cmd.sys.inprog
----------------------------------------------------------------------
/vendor/mongodb/mongodb/src/Operation/Find.php:180
#0 /vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php(558): Alcaeus\MongoDbAdapter\ExceptionConverter::toLegacy(Object(MongoDB\Driver\Exception\RuntimeException))

**Comment by Identity-labs** [comment]
I have solve with that

        $command = new \MongoDB\Driver\Command(array('currentOp' => true));
        
        $mongoClient = \MongoClient('mongodb://root:foooBarrrrr@localhost:27017?authSource=admin');
        $client = $mongoClient->getClient();
        $manager = $client->__debugInfo()['manager'];
        
        $cursor = $manager->executeCommand("admin", $command);
        $currentOp = $cursor->toArray()[0];
        
        $inprog = isset($currentOp->inprog)?$currentOp->inprog:array();

**Comment by alcaeus** [comment]
I've raised the issue in the PHP driver repository since that's where the error occurs, so there's not much I can do here.

Instead of the code you posted above, you may as well do the following:
```
$mongoClient = \MongoClient('mongodb://root:foooBarrrrr@localhost:27017?authSource=admin');
$currentOp = $client->selectDB('admin')->command(['currentOp' => true]);
```

That way you won't have to use internal methods (such as `getClient()` and `__debugInfo()` to run the command).

I've also added a note to the readme about this issues so people will know about it. Since there's nothing else I can do, I'm closing this issue.
