### ISSUE TITLE
Compatibility with Doctrine Mongo ODM

### ISSUE THREAD

**Issue by metanav** [alcaeus/mongo-php-adapter#113]
@alcaeus First of all thanks for great job!
I am planning to move one of my existing application to PHP7 and wanted to make sure if mongo-php-adapter is a (sort of) drop in replacement for the legacy driver with MongoDB ODM. Are there any known issues other than you have mentioned in the README.md?  Just a bit reluctant.

**Comment by alcaeus** [comment]
Thanks for the question. In fact, PHP 7 has been part of the ODM build pipeline for almost three months now (see doctrine/mongodb-odm#1395). In fact, it uses this library to run the tests on PHP 7 so I can say with some certainty that you should be fine. Just make sure you are running the latest stable versions (ODM 1.1.0 and doctrine/mongodb 1.3.0).
