### ISSUE TITLE
MongoCollection->aggregate makes php error with pipeline operators given as arguments

### ISSUE THREAD

**Issue by pilou** [alcaeus/mongo-php-adapter#114]
The thing is the first argument is overwritten. :(

Bad code:
```
        if (! TypeConverter::isNumericArray($pipeline)) {
            $pipeline = [];
            $options = [];

            $i = 0;
            foreach (func_get_args() as $operator) {
```
Good code:
```
        if (! TypeConverter::isNumericArray($pipeline)) {
            $operators = func_get_args();
            $pipeline = [];
            $options = [];

            $i = 0;
            foreach ($operators as $operator) {
```

If the `func_get_args` is called after`$pipeline = []`, the first value of the array will be an empty array.

Test case, and pull request is in progress.

**Comment by alcaeus** [comment]
Hah, took me a while to realise this was only occuring on PHP 7, not on 5.6. I fixed it and this will be included in the upcoming 1.0.4 release. I'm waiting for feedback on #116; once that is merged I'll release a fixed version.

**Comment by pilou** [comment]
Ohh, maybe we found a PHP bug?
I think those guys didnt intend to change the behaviour of `funct_get_args`.

**Comment by pilou** [comment]
They intended to do the change http://php.net/manual/en/function.func-get-args.php see Example #3

**Comment by alcaeus** [comment]
Thanks for following up on it, good to know 👍
