### ISSUE TITLE
Incompatible insert() signature

### ISSUE THREAD

**Issue by yunosh** [alcaeus/mongo-php-adapter#119]
MongoCollection::insert() takes the first parameter as reference, even though the documentation for that method explicitly mentions that this is not a ref: http://php.net/manual/en/mongocollection.insert.php
Thus it raises "Error: Cannot pass parameter 1 by reference" if passing a value to the method.

**Comment by alcaeus** [comment]
I've previously explained this [here](https://github.com/alcaeus/mongo-php-adapter/issues/107#issuecomment-219361205).
