### ISSUE TITLE
Error message using $set

### ISSUE THREAD

**Issue by yunosh** [alcaeus/mongo-php-adapter#121]
The following code snippet works fine with using ext/mongo directly:
```php
            $res = $this->_db->findAndModify(
                array(
                    self::SID => $id,
                    self::LOCK => array('$exists' => $exist_check)
                ),
                array($data),
                array(self::DATA => true),
                array(
                    'update' => array('$set' => $data),
                    'upsert' => !$exists
                )
            );
```
but throws the following error when using mongo-php-adapter:
> MongoResultException: exception: The dollar ($) prefixed field '$set' in '$set' is not valid for storage.

**Comment by alcaeus** [comment]
Fixing this in #122.

Out of curiosity: why are you passing both an update parameter and the update option? Normally you'd only specify one. This confused me for a moment, especially since what you're passing in the update parameter is different from what the update option would apply.

**Comment by yunosh** [comment]
No idea, that was code contributed by someone else.
