### ISSUE TITLE
Manager::selectServer(): SSL/TLS already set-up for this stream

### ISSUE THREAD

**Issue by elsenben** [alcaeus/mongo-php-adapter#123]
Hi, 

I am having an issue with an SSL connection to a replicaSet. It is the same issue as beeing discussed here (https://github.com/mongodb/mongo-php-driver/issues/328) 

Their is a fix in the mongo-php-driver release 1.1.8 but it cannot be installed with the requirements of this library. Can this be resolved? 

Kind regards, 
Ben

**Comment by alcaeus** [comment]
Works for me with 1.1.8:

```
alcaeus at vulcan in ~/Code/tmp
$ php -i | grep "mongodb version"
mongodb version => 1.1.8

alcaeus at vulcan in ~/Code/tmp
$ composer require alcaeus/mongo-php-adapter
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^1.0 for alcaeus/mongo-php-adapter
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mongodb/mongodb (1.0.2)
    Loading from cache

  - Installing alcaeus/mongo-php-adapter (1.0.5)
    Loading from cache

Writing lock file
Generating autoload files
```

What issues are you having?

**Comment by elsenben** [comment]
I am very sorry! I made a stupid mistake :) I wasn't paying enough attention and tried to update the wrong package. I upgraded the mongodb extension from pecl and everything is working now. 

Thanks!

**Comment by alcaeus** [comment]
Glad it worked!

**Comment by SashaDesigN** [comment]
I had the same - just reinstall PHP to 7.1 and install php-mongodb 1.2.9 and it solve it for me.
