### ISSUE TITLE
Call to a member function selectDatabase() on null

### ISSUE THREAD

**Issue by xprt64** [alcaeus/mongo-php-adapter#132]
I want to use mongo inside a thread and I get an error: `vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoDB.php:512 Call to a member function selectDatabase() on null`

Below is the code that produce this error
```
class WorkerThread extends \Thread
{


    private $readEvents;

    private $adapter;

    public function run()
    {
        try {
            $client = new \MongoClient();
            $dbName = 'mongo_adapter_test';

            $client->selectDB($dbName);

            $this->adapter = new MongoDbEventStoreAdapter(
                new FQCNMessageFactory(),
                new NoOpMessageConverter(),
                $client,
                $dbName
            );

            $streamName = new StreamName('Prooph\Model\User');
            $stream = $this->adapter->load($streamName);
            $readEvents = iterator_to_array($stream->streamEvents());

            echo sprintf("read %d events", count($readEvents)) . "\n";
            flush();
        } catch (\Throwable $e) {
            echo 'ERROR! ' . $e->getFile() . ':' . $e->getLine() . ' ' . $e->getMessage() . "\n";
 }
    }

    public function getReadEvents()
    {
        return $this->readEvents;
    }
}
```

A similar code, but not in a thread, works as expected.

**Comment by alcaeus** [comment]
I'm a bit at a loss here and don't have a lot of experience working with threads in PHP. Could you produce a script for me to run that will reproduce the error? Ideally in form of a unit test, but any script that I can run using `php producing-error.php` works just fine. Thanks!

**Comment by xprt64** [comment]
It was a weird thing: in my thread class I had a public variable named $adapter; after I removed things started to work. I think this was the issue.
