### ISSUE TITLE
trigger_warning parameters wrong?

### ISSUE THREAD

**Issue by kphamilton** [alcaeus/mongo-php-adapter#135]
Looking at lib/Alcaeus/MongoDbAdapter/Helper/WriteConcernConverter.php, it seems that on line 28, you are attempted to pass in E_WARNING to the trigger_warning function. Doesn't that function only allow errors in the E_USER family ([http://php.net/manual/en/function.trigger-error.php](http://php.net/manual/en/function.trigger-error.php))? So changing it to E_USER_WARNING makes it not break.

**Comment by alcaeus** [comment]
you are quite correct - passing `E_WARNING` to `trigger_error` will not work and actually trigger an `E_ERROR` about having an invalid error code. This is a bit of a problem - since changing it to E_USER_WARNING makes it behave differently from the original code. Have you run into the issue or just noticed it looking at the code?

**Comment by bensquire** [comment]
I stumbled across this earlier as I had the following set on a doctrine ODM flush:

    ['w' => true]

The error was obscured by the E_ERROR you describe. On a side note, is 'true' not a valid value for this? Setting it to 1, sorted the problem @alcaeus .

**Comment by alcaeus** [comment]
`true` is not an allowed value for the `w` option to an insert command. Looking at the [MongoDB documentation](https://docs.mongodb.com/manual/reference/write-concern/#w-option), you may pass the following:
* A number: this requires the write to have been propagated to at least the given numbers of servers. Passing a number greater than 1 is only supported in Replica sets
* The string "majority": this requires the write to have been propagated to the majority of voting nodes
* A tag set: Requires the write to have been propagated to a replica set member with the indicated tag set.

Any other options, including the boolean `true` are not valid.

**Comment by bensquire** [comment]
@alcaeus fair enough, my bad. So its just the issue reported :)

**Comment by alcaeus** [comment]
Fixed in #139. Thanks for the report!
