### ISSUE TITLE
MongoCursor::timeout is missig

### ISSUE THREAD

**Issue by nemoinho** [alcaeus/mongo-php-adapter#136]
Doctrines mongodb provides a method `timeout($ms)` which wrapps MongoCursor::timeout() to adjust the timeout of a mongo query. This is needed sometimes to increase the timeout if some huge operations are processing. The new ext-mongodb provides this via a option on the query, so the question is if it is possible to mimicry the old behaviour?

**Comment by alcaeus** [comment]
Unfortunately, the new MongoDB driver does not support setting a timeout, at least not with the same functionality as the `timeout` method in the legacy driver. To avoid any confusion, I've decided to throw a warning in `MongoCursor::timeout` to let people know the method isn't supported. You can read more about the background in #57.
