### ISSUE TITLE
\MongoId vs  \MongoDB\BSON\ObjectID within aggregate.

### ISSUE THREAD

**Issue by bensquire** [alcaeus/mongo-php-adapter#138]
Hi!

This may or may not be the place to as but I'm seeing something which I'm unable to explain and was hoping (since its related to the library) someone might be able to shed some light.

I'm on v1.0.6 of the adapter, running v1.2.0 of the MongoDB driver, PHP 7.0.13 and on the master branch of Doctrine ODM.

I'm attempting to update an aggregate I've written, so that rather than using \MongoId its uses  \MongoDB\BSON\ObjectID. The irony here is that when using the adapter equivalent of \MongoId everything works fine, but when I use \MongoDB\BSON\ObjectID, the aggregate breaks.

Am I missing something? From what I can see in the code \MongoId is just a wrapper around \MongoDB\BSON\ObjectID...

Any help appreciated!
Ben

**Comment by alcaeus** [comment]
If you could share some sample code I'd be glad to take a look! Generally speaking, you should always use the legacy classes and let the adapter do the conversion for you. This is especially true when using ODM, as it doesn't have any knowledge of the new BSON objects used by the mongodb driver.

**Comment by alcaeus** [comment]
Closing for lack of feedback. This might have been fixed by #155.
