### ISSUE TITLE
Handling authentication

### ISSUE THREAD

**Issue by Celelibi** [alcaeus/mongo-php-adapter#141]
The legacy Mongo API has a several methods of authentication.
http://php.net/manual/fr/mongo.connecting.auth.php
The only supported one is when the URI is given with the username and password. It looks like the auth method using the "username" and "password" keys to the associative array is not supported.

This should be easily fixed although care should be taken to encode the username and password to be put safely in an URI.

Best regards

**Comment by alcaeus** [comment]
I was going to implement SSH authentication in 1.1, but since none of my projects require authentication to MongoDB I haven't paid much attention to that feature. Could you post an example of what you're looking for?

**Comment by Celelibi** [comment]
Basically a call like this:
`$mongo = new \MongoClient("localhost", array('db' => "mydb", 'username' => "MyUsername", 'password' => "S3kùr€P@ssw0rd"));`
Should produce an URI like this:
`mongodb://MyUsername:S3k%C3%B9r%E2%82%ACP%40ssw0rd@localhost/mydb`
(I hope the URL encoding is right. Not tested.)

**Comment by alcaeus** [comment]
Managed to take a look - this works out of the box, I just never tested it before.

You can either pass the username in the URL (`mongodb://myUsername:secureP4ssw0rd@localhost`) or via the `username`, `password` and optionally `authSource` options (as in your example). The adapter will pass this on to the underlying driver, so there's no need to update the URl with the username from the options. Tests for this auth method will be added in 1.1.

**Comment by UCIS** [comment]
@alcaeus In the original Mongo extension the database used for authentication [could be set in the "db" option](http://php.net/manual/en/mongoclient.construct.php), while the new driver uses the "authSource" option. Shouldn't the adapter translate the db option to authSource?

I added the following code to MongoClient::__construct:
```
        if (isset($options['db'])) {
          $options['authSource'] = $options['db'];
          unset($options['db']);
        }
```

**Comment by alcaeus** [comment]
TBH, I wouldn't know - I don't use user/password authentication. If you can cook up a failing test case I'll gladly take a look.
