### ISSUE TITLE
trigger_error take E_USER_* constants

### ISSUE THREAD

**Issue by Celelibi** [alcaeus/mongo-php-adapter#142]
In several places of the code the function `trigger_error` should take `E_USER_*` (such as `E_USER_WARNING`) as second argument. Passing `E_WARNING` produce an error about the error. Which is less informative. :)

**Comment by alcaeus** [comment]
This was reported in #135 and fixed in #139. I'll release a version with fixes in the next few days.

**Comment by Celelibi** [comment]
Sorry I should have checked before.

**Comment by alcaeus** [comment]
No worries, it's a good reminder that I should tag a bugfix release 😉
