### ISSUE TITLE
Index info

### ISSUE THREAD

**Issue by sokil** [alcaeus/mongo-php-adapter#148]
When created sparse index:

```php
<?php
$collection->createIndex($array(
    'sparseAsc'     => 1,
    'sparseDesc'    => -1,
), ['sparse' => true])
```

then $collection->getIndexInfo() gives: 

```
  1 => 
  array (
    'v' => 2,
    'key' => 
    array (
      'sparseAsc' => 1,
      'sparseDesc' => -1,
    ),
    'name' => 'sparseAsc_1_sparseDesc_-1',
    'ns' => 'test.phpmongo_test_collection',
    'sparse' => true,
  ),
```

Your implementation has no parameter 'sparse' in
https://github.com/alcaeus/mongo-php-adapter/blob/master/lib/Mongo/MongoCollection.php#L706-L724
but IndexInfo has method isSparse.

Same with `expireAfterSeconds` and `textIndexVersion`.

**Comment by alcaeus** [comment]
Again, thanks for the report. #150 fixes this.
