### ISSUE TITLE
MongoDB's method createCollection, the second parameter ($options) can default to empty

### ISSUE THREAD

**Issue by quangphuc789** [alcaeus/mongo-php-adapter#152]
In MongoDB.php, line 293, createCollection() takes 2 parameters, the second parameter ($options) is required, and this is not compatible with the old MongoDB driver(s). 

However, this parameter could be default to an empty array to avoid all the discrepancies with the old driver(s).

**Comment by alcaeus** [comment]
Thanks for the report, this will be fixed in 1.0.9!

**Comment by quangphuc789** [comment]
Thank you :)
