### ISSUE TITLE
RegEx vs. MongoRegex

### ISSUE THREAD

**Issue by olvlvl** [alcaeus/mongo-php-adapter#153]
Hi,

I don't know if it belongs here, but this might be an issue. If I use `RegEx` to query a collection, I get no results:

```php
$this->dm->getDocumentCollection(Preset::class)->find([
     'name' => new \MongoDB\BSON\Regex('ol', 'i');
]);
```

Whereas if I use the old `MongoRegex` everything is fine:

```php
$this->dm->getDocumentCollection(Preset::class)->find([
    'name' => new \MongoRegex('/ol/i')
]);
```

The strangest thing is that `MongoRegex` is creating `RegEx` instances: https://github.com/alcaeus/mongo-php-adapter/blob/master/lib/Mongo/MongoRegex.php#L74

Is that expected behavior or a bug? Does it belongs here or in the [doctrine-omd](https://github.com/doctrine/mongodb-odm) repository?

**Comment by alcaeus** [comment]
It is a bug, but you shouldn't have hit it. Put simply, while you're using the adapter, I'd recommend using the legacy types, not BSON types from the new driver. Point in case, the type converter was not prepared for it and instead converted the object to a BSON document.

I've fixed this in #155, but you should still change your code to use `MongoRegex` while using ODM and the adapter.

**Comment by olvlvl** [comment]
Hi @alcaeus, shouldn't both old and new be supported so that we can begin transitioning our applications? I'd rather do this gradually then have to invest weeks to remove the adapter once the drivers are ready. What do you say?

**Comment by alcaeus** [comment]
Yes and no. Using the new BSON classes locks you into the new and old drivers at the same time, so going back to using pure ext-mongo is not possible. Of course, if that's ok for you you can always just start using BSON classes to reduce the workload. OTOH, replacing all instances of one class is relatively straightforward, especially since most BSON types don't leak out of ODM (`MongoRegex` being one of the few exceptions).

**Comment by olvlvl** [comment]
Will v1.0.9 allow mixing types?

**Comment by alcaeus** [comment]
[Yes.](https://github.com/alcaeus/mongo-php-adapter/pull/155/files#diff-f6a9075740e126df3730ee852b5e27c3R44)
