### ISSUE TITLE
PHP 7.1 -> "Attempted to load class "ObjectID" from namespace"

### ISSUE THREAD

**Issue by capozzid** [alcaeus/mongo-php-adapter#158]
I can't persist any object without having the error "Attempted to load class "ObjectID" from namespace "MongoDB\BSON".
Did you forget a "use" statement for another namespace?" 

<img width="658" alt="capture d ecran 2017-02-01 a 09 56 42" src="https://cloud.githubusercontent.com/assets/24361838/22511810/dcc26ea8-e864-11e6-94e1-a2e451ad4a4a.png">

It works well on php 7.0.13 with v1.0.9 but not on php 7.1.0

**Comment by alcaeus** [comment]
Could you provide the output of `php -m`? Also, what happens if you run the following code snippet?
```php
<?php

use MongoDB\BSON\ObjectID;

$id = new ObjectID();
```

**Comment by capozzid** [comment]
It finally seems to come from a problem of installation with mongodb and php7.1. Not an issue with mongo-php-adapter. I close the issue

**Comment by alcaeus** [comment]
Good to know, thanks for the update!
