### ISSUE TITLE
maxTimeMS support?

### ISSUE THREAD

**Issue by mmucklo** [alcaeus/mongo-php-adapter#160]
Is there any plans to support maxTimeMS in some way, given that the cursor timeout is now a no-op?

**Comment by alcaeus** [comment]
There is `MongoCursor::maxTimeMS` as per [the original class](https://secure.php.net/manual/en/mongocursor.maxtimems.php). For most methods, you should also be able to pass `maxTimeMS` as an option. Is that sufficient?

**Comment by alcaeus** [comment]
Closing due to lack of feedback.
