### ISSUE TITLE
explain() not implemented

### ISSUE THREAD

**Issue by Xosofox** [alcaeus/mongo-php-adapter#166]
I'm currently working adding "explain" to the DoctrineMongoDBBundle's profiler, so naturally this is a problem as explain() is not implemented.

Is this a "simple problem" that was just not done because it did not seem necessaary or is there a major problem to do so?

Any pointers on what to look for in doing it?

**Comment by alcaeus** [comment]
It wasn't far up my list and to be honest I also just forgot about it. If you want to get started, the starting point would be the [explain command](https://docs.mongodb.com/manual/reference/command/explain/) in MongoDB. The new cursor object in the MongoDB driver doesn't have an `explain` method, so you'll have to call the explain command yourself and format the result. Feel free to give this a crack, let me know if I can be of any help.
