### ISSUE TITLE
Why is not overriding the original mongodb class?

### ISSUE THREAD

**Issue by celvin** [alcaeus/mongo-php-adapter#172]
test_find_success
Error: Call to undefined method MongoDB\Driver\Cursor::fields()

I have installed it with composer into a laravel project, but is not looking at the adapter MongoDB class

**Comment by alcaeus** [comment]
I'm not sure what you are talking about. The `MongoDB\Driver\Cursor` class doesn't have a `fields` method, and the adapter isn't calling one either. A stack trace and some sample code that reproduces the error would be helpful.

**Comment by alcaeus** [comment]
Closing due to lack of feedback.

**Comment by celvin** [comment]
I'm sorry, my computer was broken, I meant:

Your adapter should take place instead of MongoDB\Driver\Cursor

https://github.com/alcaeus/mongo-php-adapter/blob/4b6720a1c312502e72c36f0336c09c3976603aab/lib/Mongo/MongoCursor.php

the fields method is in MongoCursor.php

**Comment by alcaeus** [comment]
I'm sorry. I still haven't understood what you're talking about. `MongoCursor` has a fields method and as far as I know, the adapter replicates the functionality of the legacy driver in this case.

Without some code or a better explanation of what exactly you tried to do and what happened there's nothing I can do.
