### ISSUE TITLE
Implement MongoCollection class

### ISSUE THREAD

**Issue by alcaeus** [alcaeus/mongo-php-adapter#2]
- [ ] Implement missing methods

**Comment by RageZBla** [comment]
I'll give this one a shot to start!

**Comment by alcaeus** [comment]
Great! I've created #9 to track work on MongoCommandCursor, that will include the two aggregation methods in MongoCollection.

**Comment by alcaeus** [comment]
Merged in https://github.com/alcaeus/mongo-php-adapter/commit/c971cb467907fafc42789aa5e349521d59954a27. Thanks @RageZBla!
