### ISSUE TITLE
Installation manual

### ISSUE THREAD

**Issue by vkhramtsov** [alcaeus/mongo-php-adapter#205]
Hello,

Currently you suggest to use `--ignore-platform-reqs` command line switch as workaround for installation issues. What do you think about adding emulation of `ext-mongo` in composer.json file in `config.platform` (https://getcomposer.org/doc/06-config.md#platform) section? This workaround disable only check for particular modules instead of completely disable platform checks.

**Comment by alcaeus** [comment]
Good idea. I'll do some testing and update accordingly if it works as I'm hoping it will.

**Comment by vkhramtsov** [comment]
I can create PR for this. Actually I'm using this way in my project 🙂

**Comment by alcaeus** [comment]
Please do.
