### ISSUE TITLE
document to insert contains invalid key: keys cannot contain "." for all mongodb >= 1.3

### ISSUE THREAD

**Issue by necromant2005** [alcaeus/mongo-php-adapter#209]
For mongodb driver higher version 1.3 convertor fails on insert with message "document to insert contains invalid key: keys cannot contain ".""

Core of issue in TypeConvertor.php line 160
```
    private static function convertBSONObjectToLegacy(BSON\Type $value)
    {
        switch (true) {
            case $value instanceof BSON\ObjectID:
                return new \MongoId($value);
```
[PHPC-1004] - Rename ObjectID to ObjectId => http://pecl.php.net/package-changelog.php?package=mongodb

That's why the correct code:
```
    private static function convertBSONObjectToLegacy(BSON\Type $value)
    {
        switch (true) {
            // mongo-driver >= 1.3
            case $value instanceof BSON\ObjectId:
                return new \MongoId($value);
            // mongo-driver < 1.3
            case $value instanceof BSON\ObjectID:
                return new \MongoId($value);
```

Also it requires to apply similar fixes to 4 other places.

**Comment by alcaeus** [comment]
Can you please provide a failing test case? Current travis builds pass on 1.3 and I haven’t seen the error before. Class names also aren’t case-sensitive in PHP (only autoloading may ne die to file system restrictions), so the wrong case for ObjectId shouldn’t be the cause of this either.

**Comment by emirb** [comment]
I say this is not related to the adapter but to Mongo PHP extension itself.

Starting with 1.3.0, [Driver should validate BSON documents before insert and update](https://jira.mongodb.org/browse/PHPC-712): (related PR: https://github.com/mongodb/mongo-php-driver/pull/524)

**Comment by alcaeus** [comment]
Closing for lack of feedback.
