### ISSUE TITLE
install mongo-php-adapter on php 7 

### ISSUE THREAD

**Issue by pedramham** [alcaeus/mongo-php-adapter#225]
I try to install mongo-php-adapter over composer but drops me

`$ composer require alcaeus/mongo-php-adapter`

```
  Problem 1
    - alcaeus/mongo-php-adapter 1.1.5 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.4 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for alcaeus/mongo-php-adapter ^1.1 -> satisfiable by alcaeus/mongo-php-adapter[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\wamp64\bin\php\php7.0.10\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

```
how i can install **mongo-php-adapter**

> **Additional information**
>  MongoDB extension version 1.4.2
>  php 7.0.10
Symfony 3.4 Flex
 sonata-admin-bundle": "^3.33"

**Comment by alcaeus** [comment]
How did you get the "additional information" you posted in the issue? I assume this is from a phpinfo page somewhere. Please confirm that you have the mongodb extension enabled in your CLI by running `php -m` and ensuring it is listed. Most likely it isn't installed, as that's usually the case for the error message you posted. Thanks.

**Comment by pedramham** [comment]
It is right.i have mnogo on **php info**.but it is not enabled .I have not it on list.when running **php -m**.
thank you so much

**Comment by sarthak-patidar** [comment]
I have enabled mongodb extension, still i get those error messages. How do i fix it? Thanks in advance.

**Comment by sarthak-patidar** [comment]
running **php -m**  shows that the extension is installed, error message tells that version 1.1.5 is installed but when i try to run **pecl update mongodb** it says that newest version 1.4.3 is installed.
Am i missing something here or doing something wrong.

**Comment by alcaeus** [comment]
@sarthak-patidar what environment are you on? Could it be that pecl installs the package to a different PHP version than the one that's running when running `php -m`? That's the only thing I can come up with that would cause such an issue.

**Comment by 10secondsofcode** [comment]
Follow the below steps, it will resolve this issue.

```
sudo apt-get install php7.2-dev
sudo apt-get install libcurl4-openssl-dev pkg-config libssl-dev libsslcommon2-dev
sudo apt-get install php-pear
sudo pecl install mongodb

```
**Link:** https://stackoverflow.com/questions/51268761/requires-ext-mongodb-1-5-0-symfony/52039006#52039006

**Comment by raysk4ever** [comment]
how to enable if not showing in the list running the command php -m

**Comment by alcaeus** [comment]
@raysk4ever instead of resurrecting an old issue, please create a new issue, adding information regarding the problem you're facing: what have you tried, what errors are you getting, and so on. Thanks!
