### ISSUE TITLE
cursor id 143376502446 not found

### ISSUE THREAD

**Issue by pesseyjulien** [alcaeus/mongo-php-adapter#227]
Hi,

I'm getting the following error and I don't really know why :

`cursor id 143376502446 not found" {"exception"    :"[object] (MongoDB\\Driver\\Exception\\RuntimeException(code: 43): cursor id 143376502446 not found at /srv/www/back-football/releases/29052018-154641/current/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCursor.php:479)"`

Thanks in advance for your help,
Julien

**Comment by pesseyjulien** [comment]
I see, well I won't be able to provide you with a script, but I can give you an example of queries I execute ?

Essentially what I'm doing :

- get documents with query
- loop on documents
- merge & flush each document in loop, after executing some code with the document info

Any cursor for you in this ?

**Comment by alcaeus** [comment]
> Any cursor for you in this ?

Yes - the `find` command will yield a cursor which you will then iterate. As suggested above, the cursor can time out after a certain inactivity period. Depending on what you do while iterating over the query results, this could easily happen. If you expect the whole process of handling documents to take more than 10 minutes, try setting the `noCursorTimeout` option when issuing the `find` command.

**Comment by alcaeus** [comment]
Those options aren't correct - you want to specifically disable cursor timeouts using the `noCursorTimeout` when running a `find` command. However, it seems that isn't possible using the query builder in Doctrine MongoDB ODM since those options aren't passed down to the driver. I've created https://github.com/doctrine/mongodb-odm/issues/1808 to track this in ODM.

Apart from that, how long does the query actually run? Is this a case of actually running into the 10-minute timeout?

**Comment by pesseyjulien** [comment]
Alright, thanks a lot !

Well I'm not sure because it's pretty random. I'm running this command every 10min, but it only happened once yesterday. And like 2min after the command started.

So might be some temporary issue(s) with the database ?

**Comment by pesseyjulien** [comment]
Well, it's not happening anymore. Might have been the database !

Closing it, thanks for the help !

**Comment by jmikola** [comment]
@pesseyjulien: I realize the issue went away for you, but do you recall if you were using MongoDB 3.6 at the time this originally popped up? I wonder if it might have been related to https://github.com/mongodb/mongo-php-driver/issues/825, which is tracking some issues the server had with prematurely ending sessions (and any associated resources, such as cursors).
