### ISSUE TITLE
PHP 7.1 Support

### ISSUE THREAD

**Issue by alexandru-porcescu** [alcaeus/mongo-php-adapter#228]
Hello alcaues,

I want to start by thanking you for the amazing polyfill. 
I have a questions why limit the adapter to 5.6 or 7.0?

I am trying to update a symfony app to php 7.1 and encountering issues.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/mongodb-odm-bundle 3.4.0 requires doctrine/mongodb ^1.4 -> satisfiable by doctrine/mongodb[1.6.1, 1.4.0, 1.5.0, 1.6.0, 1.6.2].
    - doctrine/mongodb-odm-bundle 3.3.0 requires doctrine/mongodb ^1.4 -> satisfiable by doctrine/mongodb[1.6.1, 1.4.0, 1.5.0, 1.6.0, 1.6.2].
    - doctrine/mongodb-odm-bundle 3.4.0 requires doctrine/mongodb ^1.4 -> satisfiable by doctrine/mongodb[1.6.1, 1.4.0, 1.5.0, 1.6.0, 1.6.2].
    - doctrine/mongodb-odm-bundle 3.4.1 requires doctrine/mongodb ^1.4 -> satisfiable by doctrine/mongodb[1.6.1, 1.4.0, 1.5.0, 1.6.0, 1.6.2].
    - doctrine/mongodb-odm-bundle 3.4.2 requires doctrine/mongodb ^1.4 -> satisfiable by doctrine/mongodb[1.6.1, 1.4.0, 1.5.0, 1.6.0, 1.6.2].
    - doctrine/mongodb-odm-bundle 3.4.3 requires doctrine/mongodb ^1.4 -> satisfiable by doctrine/mongodb[1.6.1, 1.4.0, 1.5.0, 1.6.0, 1.6.2].
    - doctrine/mongodb-odm-bundle 3.4.4 requires doctrine/mongodb ^1.4 -> satisfiable by doctrine/mongodb[1.6.1, 1.4.0, 1.5.0, 1.6.0, 1.6.2].
    - doctrine/mongodb 1.6.1 requires ext-mongo ^1.6.7 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
    - doctrine/mongodb 1.4.0 requires ext-mongo ^1.5 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
    - doctrine/mongodb 1.5.0 requires ext-mongo ^1.5 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
    - doctrine/mongodb 1.6.0 requires ext-mongo ^1.6.7 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
    - doctrine/mongodb 1.6.1 requires ext-mongo ^1.6.7 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
    - doctrine/mongodb 1.6.2 requires ext-mongo ^1.6.7 -> satisfiable by alcaeus/mongo-php-adapter[1.1.3].
    - Conclusion: remove alcaeus/mongo-php-adapter 1.1.3
    - Installation request for doctrine/mongodb-odm-bundle ^3.3 -> satisfiable by doctrine/mongodb-odm-bundle[3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4].

 `
I appreciate the time reading this.

**Comment by alcaeus** [comment]
As you can see in composer.json, the set of PHP versions is not limited to 5.6 and 7.0 but 5.6 and any later 5.x release and 7.0 or any later 7.x release:
`"php": "^5.6 || ^7.0",`

In your case, I would guess that you are running into the platform package `provides` issue with composer. Did you follow the installation instructions? It looks like you forgot to run
`composer config "platform.ext-mongo" "1.6.16"`.

**Comment by alexandru-porcescu** [comment]
Hei, thank you for taking the time, altough it was a noob question. I appreciate it. 
Have a great day.
