### ISSUE TITLE
Compatibility with doctrine odm

### ISSUE THREAD

**Issue by bazo** [alcaeus/mongo-php-adapter#23]
Hi,

when used with doctrine odm the function MongoCollection::batchInsert, more precisely the call to $this->collection->insertMany() raises an error because a stdClass is passed instead of arrays

this is a very quick fix done on directly on my server
````php
    $data = (array)array_values((array)TypeConverter::fromLegacy($a))[0];
    $data = [$data];
		
     $result = $this->collection->insertMany(
		$data,
            //(array) TypeConverter::fromLegacy($a),
            $this->convertWriteConcernOptions($options)
     );
````

maybe this will help someone

**Comment by alcaeus** [comment]
Thanks for the report, I didn't see ODM actually passes an array with non-numeric keys.
