### ISSUE TITLE
Dependency problems when i try to update

### ISSUE THREAD

**Issue by etshy** [alcaeus/mongo-php-adapter#232]
HI, I have a dependency problem when I try to update (didn't have the problem like 3 or 4 months ago)
```
- Installation request for alcaeus/mongo-php-adapter ^1.1@dev -> satisfiable by alcaeus/mon
  go-php-adapter[1.1.x-dev].
- alcaeus/mongo-php-adapter 1.1.x-dev requires mongodb/mongodb ^1.0.1 -> no matching packag
  e found.

 Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to your minimum-stability
  setting
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
   - It's a private package and you forgot to add a custom repository to find it
```

since the last update I made few months ago, I just added some doctrineExtensions package, I don't think that's the cause of the problem.

**Comment by applestump** [comment]
I too ran into this problem today, when previously this had worked fine. I found that removing the ./vendor directory and composer.lock, then running a composer install seemed to rectify it.

`rm -Rf ./vendor
rm composer.lock
composer install`

Not a satisfying fix, as it would be nice to know the exact issue. Can you try and confirm whether this fixes the problem for you?

**Comment by etshy** [comment]
yep that worked.
Weird that the update is not working, but thank you.

**Comment by etshy** [comment]
hmm I didn't take note of the version I had, sorry.
for `alcaeus/mongo-php-adapter` : surely the 1.1.4
for `mongodb/mongodb` : 1.3.1 I _think_
and for `ext-mongodb` : here is a screenshot of my php_info : https://puu.sh/ARWHY/67e475627f.png (I don't think the `composer update` the php extension, it should be right.)

**Comment by alcaeus** [comment]
Closing here: from what I can see, using the current suggested method of `config.platform` along with a regular `require` directive in composer.json should work in all cases. If it breaks, it's most likely not because of this package.
