### ISSUE TITLE
Error with mongodb 3.6

### ISSUE THREAD

**Issue by rrobinpro** [alcaeus/mongo-php-adapter#235]
Hello,

I have upgrade my mongodb on 3.6 and i have this error : 
`request.CRITICAL: Uncaught PHP Exception MongoCursorException: "Unknown modifier: $pushAll" at /srv/app/vendor/alcaeus/mongo-php-adapter/lib/Alcaeus/MongoDbAdapter/ExceptionConverter.php line 83`

https://docs.mongodb.com/v3.6/release-notes/3.6/#removed-operators

Thanks

**Comment by alcaeus** [comment]
This is an application issue: just don't use `pushAll` - nothing I can do about this.
