### ISSUE TITLE
PHP Mongo Adapter with Symfony 4

### ISSUE THREAD

**Issue by timusiiit123** [alcaeus/mongo-php-adapter#237]
dell123@Dell MINGW64 /c/symfony-project
$ composer require alcaeus/mongo-php-adapter
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_mongo.dll' (tried: C:\xampp\php\ext\php_mongo.dll (The specified module could not be found.), C:\xampp\php\ext\php_php_mongo.dll.dll (The specified module could not be found.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'php_mongo.dll' (tried: C:\xampp\php\ext\php_mongo.dll (The specified module could not be found.), C:\xampp\php\ext\php_php_mongo.dll.dll (The specified module could not be found.)) in Unknown on line 0
Using version ^1.1 for alcaeus/mongo-php-adapter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - alcaeus/mongo-php-adapter 1.1.5 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.4 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.3 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - alcaeus/mongo-php-adapter 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for alcaeus/mongo-php-adapter ^1.1 -> satisfiable by alcaeus/mongo-php-adapter[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by alcaeus** [comment]
Please try to describe your problem and the steps you took to solve it instead of dumping unformatted shell output without context. Thanks.
