### ISSUE TITLE
The 'cursor' option is required, except for aggregate with the explain argument 

### ISSUE THREAD

**Issue by Djackg** [alcaeus/mongo-php-adapter#238]
Hi,

when we are using mongodb 3.6, exception was throw, when aggregate command was executed

exception 'MongoDB\Driver\Exception\CommandException' with message 'The 'cursor' option is required, except for aggregate with the explain argument' in vendor/mongodb/mongodb/src/Operation/Aggregate.php:263
Stack trace:
#0 vendor/mongodb/mongodb/src/Operation/Aggregate.php(263): MongoDB\Driver\Server->executeReadCommand('score8', Object(MongoDB\Driver\Command), Array)
#1 vendor/mongodb/mongodb/src/Collection.php(223): MongoDB\Operation\Aggregate->execute(Object(MongoDB\Driver\Server))
#2 vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php(165): MongoDB\Collection->aggregate(Array, Array)

Google said that in mongodb 3.6 aggregate cmd requires cursor option, and useCursor is dropped.

Its planned to support mongodb in version higher than 3.4 ?

**Comment by alcaeus** [comment]
Duplicate of #226, see 
https://github.com/alcaeus/mongo-php-adapter/issues/226#issuecomment-379975982. Closing as `wontfix`.
