### ISSUE TITLE
The values 'skip' and 'limit' always set to 0 in getCursorInfo (MongoCommandCursor)

### ISSUE THREAD

**Issue by alanpoulain** [alcaeus/mongo-php-adapter#239]
In the following code, `skip` and `limit` are set to 0:
https://github.com/alcaeus/mongo-php-adapter/blob/ae806ac488c021dfe1be5af2abf0ce62376058f7/lib/Mongo/MongoCommandCursor.php#L88-L99
Is it impossible to retrieve their true values somehow like it's done in `MongoCursor`? Is it a limitation of https://github.com/mongodb/mongo-php-library or is it simply a matter of work to be done?

**Comment by alcaeus** [comment]
Unfortunately, those values are not easily available using the new API and thus are not provided, similar to the `numReturned` property. This can't easily be fixed.
