### ISSUE TITLE
What is the plan for the latest drivers?

### ISSUE THREAD

**Issue by shanghaiyangming** [alcaeus/mongo-php-adapter#241]
What is the plan for the latest drivers? e.g. mongodb 1.4+or1.5+

**Comment by shanghaiyangming** [comment]
I know that some new functions have been added that were not in the original driver, but whether it is planned to provide extensions other than compatible with the old drivers, so that the library can continue to function in addition to compatibility.

**Comment by alcaeus** [comment]
This library will always only provide functionality that the legacy driver provided. If you need to use more than that, use `ext-mongodb` natively.
