### ISSUE TITLE
no such cmd: listIndexes

### ISSUE THREAD

**Issue by plashenkov** [alcaeus/mongo-php-adapter#248]
Hi!

I'm trying to use your adapter with https://github.com/thephpleague/flysystem-gridfs and I get this error: `no such cmd: listIndexes`. It looks like listIndexes introduced in Mongo 3.0.0, while the server I'm working with uses Mongo 2.6.

How to get out of this situation? Is your adapter for Mongo 3 only?

Thank you!

**Comment by alcaeus** [comment]
The adapter needs the `listIndexes` command to be able to provide the `MongoCollection::getIndexInfo` method. It's not possible to replicate this any other way, so if you're getting that error it means that you're going to need to update to a newer version of MongoDB.
