### ISSUE TITLE
ErrorException "continue" targeting

### ISSUE THREAD

**Issue by benoitpetit** [alcaeus/mongo-php-adapter#254]
![Screenshot_6](https://user-images.githubusercontent.com/40871744/61383489-19f8f500-a8af-11e9-9e2a-0ebcaf00c3f1.png)

> Hello small problem with the command _is necessary to run Doctrine MongoDB ODM with PHP7_

**Comment by alcaeus** [comment]
There is no `continue` within a `switch` in this project. You'll have to either disable the Symfony Error Handler or run composer in verbose mode to hopefully get a trace for the exception.

Closing as the error is not related to the library.
