### ISSUE TITLE
Root package 'alcaeus/mongo-php-adapter' cannot require itself in its composer.json

### ISSUE THREAD

**Issue by rosslyn-alexadamovici** [alcaeus/mongo-php-adapter#256]
When running composer config "platform.ext-mongo" "1.6.16" && composer require alcaeus/mongo-php-adapter , I get the following:

Using version ^1.1 for alcaeus/mongo-php-adapter
Root package 'alcaeus/mongo-php-adapter' cannot require itself in its composer.json

Any help would be appreciated.

**Comment by alcaeus** [comment]
Can you please post the `name` portion of your `composer.json`?

**Comment by rosslyn-alexadamovici** [comment]
"name": "alcaeus/mongo-php-adapter"

**Comment by alcaeus** [comment]
And there's the cause of your issue: your own `composer.json` declares the same name for your package as one that you're requiring (which is what the error message is telling you). You need to use your own project name in your own composer.json, not reuse that of an existing package.

**Comment by gurpreetkaits** [comment]
Thanks @alcaeus
