### ISSUE TITLE
Missing Countable implementation in MongoCursor

### ISSUE THREAD

**Issue by marcinrosinski** [alcaeus/mongo-php-adapter#258]
It appears `MongoCursor` needs to implement `Countable` https://www.php.net/manual/en/class.countable.php as otherwise things like the following are no longer working:

```
$flaggs = $mongo->db->collection->find(array(
	'foo'	=> 'bar' 
));

echo count($flaggs);
```

they throw `Warning: count(): Parameter must be an array or an object that implements Countable` and if used in `if` will always return `false`

Tested in PHP 7.3

**Comment by marcinrosinski** [comment]
Added pull request - https://github.com/alcaeus/mongo-php-adapter/pull/259

**Comment by marcinrosinski** [comment]
Thanks @alcaeus do you have some ETA on when tag 1.1.10 will be deployed?

Thanks,
/Marcin

**Comment by alcaeus** [comment]
I'll tag a new release soon - just want to investigate another small thing I noticed.
