### ISSUE TITLE
install mango php adapter with composer and use php.ini

### ISSUE THREAD

**Issue by muhammedInan** [alcaeus/mongo-php-adapter#266]
Hi,

    - alcaeus/mongo-php-adapter 1.1.4 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.

when I launch the command for install this require , I have this error howewer I add php_mangodb.dll in php.ini and in php/ext. In my composer .json its ^1.2.0

After try php-m I have nothing about mango 

what more should i do please .

**Comment by alcaeus** [comment]
Hi,

please refrain from creating multiple issues for the same problem. If the MongoDB extension is listed when calling `phpinfo()` from the web SAPI, I would assume that you need to add the extension to a separate ini file for the CLI SAPI. You can check this by running `php --ini` and looking at the files that PHP loads, then add the extension line if it's missing. For further information, please read https://github.com/mongodb/mongo-php-driver/issues/822 as that deals with the same issue as you're encountering. If this does not fix the problem, please check other issues regarding the same problem in https://github.com/mongodb/mongo-php-driver/issues. I'm closing this as it's not a problem with the adapter but with the MongoDB driver.
