### ISSUE TITLE
support for NO_MAX_STALENESS and  SMALLEST_MAX_STALENESS_SECONDS for readPreference

### ISSUE THREAD

**Issue by eugenejen** [alcaeus/mongo-php-adapter#269]
it seems like since mongo has two new readPreference settings that are available in the driver
https://www.php.net/manual/en/class.mongodb-driver-readpreference.php

But current Alcaeus driver did not support those preferences.

There are some use case for this two in some environment that use secondary to mitigate load on primary. but if replication lag happens due to different reasons, the SMALLEST_MAX_STALENESS_SECONDS will make driver to contact the secondary or primary to read the data by the staleness seconds or just ignore staleness completely.

**Comment by alcaeus** [comment]
Read preference in the legacy driver only supported a type (now called mode) and tag sets. The "maxStalenessSeconds" option is not supported by that driver, so I'm not sure what you expect to happen here.

**Comment by eugenejen** [comment]
@alcaeus thanks for replying. the code that I had issues is use Alcaeus driver to maintain backward compatibilities. But now it has a new version of driver but the code build op top of the Alcaeus driver can be hard to change. I guess maybe one day that project can just use mongodb driver directly.

Since this issue seems won't be changed. I am closing the issue.
