### ISSUE TITLE
Whether the latest version of Ext-mongodb is supported

### ISSUE THREAD

**Issue by shanghaiyangming** [alcaeus/mongo-php-adapter#284]
Whether the latest version of Ext-mongodb is supported

**Comment by shanghaiyangming** [comment]
![image](https://user-images.githubusercontent.com/712222/128981405-6066c45b-6160-42b8-b750-eacefe053a2f.png)

**Comment by shanghaiyangming** [comment]
I have installed the latest version of the driver, and found that it can also be successfully upgraded through Composer, but what is the availability of specific features?  In config in Composer, ext-mognodb is ^1.2.0

**Comment by shanghaiyangming** [comment]
Or can I use the latest driver and continue to use the old script as long as I don't use the new features of the new mongodb version?

**Comment by shanghaiyangming** [comment]
Sorry, wrong understanding, no problem excuse me

**Comment by alcaeus** [comment]
This library provides the functionality of the legacy driver, built on top of the current driver. This was done to bring PHP 7 compatibility to ODM 1.x. As the feature set to support is defined by the legacy driver which is no longer supported. ODM 1.x will (mostly) work with MongoDB 5.0, but you most likely won't be able to make use of all features if you use ODM 1.x.
