### ISSUE TITLE
ns field deprecated

### ISSUE THREAD

**Issue by astuerze** [alcaeus/mongo-php-adapter#286]
**MongoDB Version 4.4:**
The listIndexes and the mongo shell helper method db.collection.getIndexes() no longer returns the namespace ns field in the index specification documents.

**Source:**
https://docs.mongodb.com/manual/release-notes/4.4/

**Code:**
https://github.com/alcaeus/mongo-php-adapter/blob/1.x/lib/Mongo/MongoCollection.php 
Line 720: 'ns' => $indexInfo->getNamespace(),

**Comment by alcaeus** [comment]
This library replicates the legacy MongoDB extension, which does not support any MongoDB versions newer than 3.6. So as long as your code runs on newer versions without upgrading, that's fine, but I will not be working around issues that crop up on newer MongoDB versions.
