### ISSUE TITLE
PHP 8.1.0, a class which implements Serializable deprecated

### ISSUE THREAD

**Issue by Defender32** [alcaeus/mongo-php-adapter#289]
PHP 8.1.0, a class which implements Serializable deprecated. MongoId implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

**Comment by shanghaiyangming** [comment]
Deprecated: MongoId implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in D:\MyCode\iwebsite2php8\vendor\alcaeus\mongo-php-adapter\lib\Mongo\MongoId.php on line 23

In PHP 8.1.6 the problem still exists, the version has been upgraded to 1.2.2, the problem does not seem to be solved.Can you help solve it

**Comment by alcaeus** [comment]
Please see https://github.com/alcaeus/mongo-php-adapter/pull/290#issuecomment-1030329398.
