### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by Nickolay-Kehayov** [alcaeus/mongo-php-adapter#292]
Hello.
I saw that in commit https://github.com/alcaeus/mongo-php-adapter/commit/0e99bf5ea15f8e9b7ddb3a6dc38c11aa95330ca1 , the compatibility with PHP 8.1 is improved , but there are still deprecated errors, it would seem.
in PHP 8.1.5 i get the following:

Deprecated: MongoId implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoId.php on line 23

Is there something that i am missing ? 
Thank you in advance.

**Comment by alcaeus** [comment]
Please see https://github.com/alcaeus/mongo-php-adapter/pull/290#issuecomment-1030329398.
