### ISSUE TITLE
Version 1.2.4 introduces regression

### ISSUE THREAD

**Issue by shokre** [alcaeus/mongo-php-adapter#303]
Version 1.2.4 introduces regression with error `Required 'ns' option is missing from index specification`

AFAICT error is introduced in `lib/Mongo/MongoCollection.php` with replacement of `\MongoDB\generate_index_name($keys);` with `$this->generateIndexName($keys);`

Versions 1.2.3 and below work ok.

[Tag diff](https://github.com/alcaeus/mongo-php-adapter/compare/1.2.3...1.2.4)

PHP: v7.2.34-33+ubuntu18.04.1+deb.sury.org+1
MongoDB server: 3.4.x
```
# composer show | grep mong
alcaeus/mongo-php-adapter          1.2.4   Adapter to provide ext-mongo interface on top of mongo-php-library
mongodb/mongodb                    1.6.1   MongoDB driver library
```

**Comment by Hemric** [comment]
Same here with 1.2.4, php 5.6 and mongodb 4.4 !
