### ISSUE TITLE
PHP 8.2 Error TypeConverter and MongoId

### ISSUE THREAD

**Issue by juizmill** [alcaeus/mongo-php-adapter#304]
An error is being generated due to the migration to PHP 8.0

![image](https://github.com/alcaeus/mongo-php-adapter/assets/1959742/1bf5a1cf-aadc-474d-a13a-4200d5c995ff)

https://github.com/alcaeus/mongo-php-adapter/blob/1.2.4/lib/Alcaeus/MongoDbAdapter/TypeConverter.php#L180

![image](https://github.com/alcaeus/mongo-php-adapter/assets/1959742/13af679b-7322-4c2b-832c-548901c0af36)

https://github.com/alcaeus/mongo-php-adapter/blob/1.x/lib/Mongo/MongoId.php

How can we fix this problem?

**Comment by alcaeus** [comment]
Please see https://github.com/alcaeus/mongo-php-adapter/pull/290#issuecomment-1030329398.

This package was created to allow users to update to PHP 7 without having to migrate to the new MongoDB driver **first**. The last MongoDB version supported by the legacy driver is MongoDB 3.2, which is no longer supported by the new driver. Please fork the library, adapting and maintaining it for your use case, or use the supported MongoDB driver. The package will not be updated for any future PHP versions.
