### ISSUE TITLE
PHP Version Support

### ISSUE THREAD

**Issue by alcaeus** [alcaeus/mongo-php-adapter#308]
This library was initially created to facilitate migrating applications using the Doctrine MongoDB ODM to PHP 7 while the team was working on replacing the internals to suit the new MongoDB driver (`ext-mongodb`). With PHP 7 no longer being supported, and the last MongoDB versions officially supported by the legacy driver (`ext-mongo`), which this library emulates, the time has come to retire this library.

If you are using this library with PHP 8, you should have upgraded to the new MongoDB driver a while ago. Recent changes in PHP made maintaining compatibility with the legacy driver (which is a must for this library) impossible, so any future PHP version will cause you more headaches. Note that while the library can be installed on PHP 8, I will most likely not want to fix any issues caused solely by a newer PHP version.

If you are using an older PHP version, you should upgrade to the new driver before upgrading your PHP version any further. Please refer to the following table for the latest extension version that supports your PHP version:
| PHP version | Latest extension version |
| --- | --- |
| 5.6 | 1.7.4 |
| 7.0 | 1.9.1 |
| 7.1 | 1.11.1 |
| 7.2 | 1.16.2 |
| 7.3 | 1.16.2 |

The following pull requests will be accepted going forward:
* Fixes for incorrect behaviour compared to the legacy extension
* Security issues, regardless of PHP version used
* Data integrity issues, as long as no BC breaks compared to the legacy driver occur.

All other pull requests will be rejected. No attempts at maintaining compatibility with future PHP versions will be made. If you need to continue using this library on a newer PHP version, please fork this repository and maintain the library yourself going forward.

**Comment by pmaselkowski** [comment]
Thanks for announcing this much earlier, so there was time to migrate to the new library. I recommend this to anyone still using this adapter to migrate to new library, it's not that hard as it seems.
