### ISSUE TITLE
Serializable interface is deprecated

### ISSUE THREAD

**Issue by dragu** [alcaeus/mongo-php-adapter#311]
/var/www/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoId.php [23]:

										
MongoId implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

**Comment by alcaeus** [comment]
This will not be fixed, see https://github.com/alcaeus/mongo-php-adapter/issues/308 for more details.
