### ISSUE TITLE
This is amazing project~

### ISSUE THREAD

**Issue by shanghaiyangming** [alcaeus/mongo-php-adapter#44]
May I join the development？

**Comment by alcaeus** [comment]
There is currently stabilization work being done in #28 to make sure the library behaves as close to `ext-mongo` as possible. Right now there isn't much you can do unless you're willing to fix some of the failing tests. In that case: fork the repository, branch off the `run-ext-mongo-tests` branch and create a PR back to it once you've made your changes.
