### ISSUE TITLE
Implement MongoLog

### ISSUE THREAD

**Issue by alcaeus** [alcaeus/mongo-php-adapter#5]
- [ ] Implement missing methods

**Comment by RageZBla** [comment]
@alcaeus this one looks like pretty much same deal as Mongo class, may I got ahead and make all the methods throw the Not implemented and mention that in the README?

**Comment by alcaeus** [comment]
@RageZBla not quite - I did that for the Mongo class since it has been deprecated with `MongoClient`, `MongoDB` and `MongoPool`. `MongoLog` on the other side is not deprecated and still wanting to be used.

**Comment by alcaeus** [comment]
@RageZBla took another look at the `MongoLog` class and how it's used in the driver. I'd say for now we implement the functionality of the class itself (storing levels and the log callback) but hold off on actually making any calls for logging. I took a look at the driver and some of the messages are quite low-level (infos about data being parsed, etc.). I'm not sure we can replicate that to the point where it behaves like it does now.
