### ISSUE TITLE
aggregate without cursor not working

### ISSUE THREAD

**Issue by alcaeus** [alcaeus/mongo-php-adapter#50]
This is due to a bug in mongo-php-library which will be fixed when mongodb/mongo-php-library#107 is merged.

**Comment by jmikola** [comment]
mongodb/mongo-php-library#107 is merged and awaiting release in 1.0.1.

**Comment by alcaeus** [comment]
Thanks @jmikola! I'm leaving this open until 1.0.1 drops.

**Comment by jmikola** [comment]
FYI: [1.0.1](https://github.com/mongodb/mongo-php-library/releases/tag/1.0.1) is tagged with the necessary fix.
