### ISSUE TITLE
MongoCursor::timeout()

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [alcaeus/mongo-php-adapter#57]
The new mongo driver does not ship with a way to set a cursor timeout. It seems like there is this functionality in the C driver though. There is now a ticket for this: https://jira.mongodb.org/browse/PHPC-576

Once that ticket is resolved, we should be able to set the timeout in the adapter as well.

**Comment by jmikola** [comment]
I was on holiday last week, so apologies for the delayed response. The C driver doesn't actually support this (the referenced function had to do with `maxTimeMS` on tailable cursor `getMore` requests), so it won't be possible without constructing new clients from customized URIs.

**Comment by alcaeus** [comment]
@jmikola So, if I understand you correctly, the functionality previously provided by `MongoCursor::timeout` won't be implemented in `ext-mongodb` or `mongo-php-library`?

**Comment by jmikola** [comment]
@alcaeus: That's correct. I'm not sure how best to handle this in the adapter between NOP-ing, throwing an exception, or emitting a warning/notice.

**Comment by alcaeus** [comment]
I think emitting a warning and NOP-ing after that is the smartest choice. That way people will know that cursor timeouts are not longer supported but their code won't error out.
