### ISSUE TITLE
How to set driverOptions ?

### ISSUE THREAD

**Issue by acrozes** [alcaeus/mongo-php-adapter#80]
I am testing to connect to a mongod with ssl and uncertified certificate.
How can I set the $driverOptions in "mongo-php-adapter\lib\Mongo\MongoClient.php" constructor ? I don't see any parameters in the bundle to do it.

I'd like to create a stream context as explain at http://php.net/manual/fr/mongo.connecting.ssl.php ... or maybe there is a better way to do ?

**Comment by alcaeus** [comment]
This library is intended to be a drop-in replacement for the legacy mongo driver (`ext-mongo`) with the goal being that (most) things that worked in the driver will still work. You should be able to run the code from the example above against this library with the same result as you would have running it against the driver.

A quick look into the new MongoDB driver code tells me that the new driver still accepts the `context` parameter to pass a stream context with options set: https://github.com/mongodb/mongo-php-driver/blob/7d6151376f590277280660dab58649fab22e4fa2/php_phongo.c#L1962..L1971. Can you give this a try and let me know if it works? Thanks!

**Comment by acrozes** [comment]
I am sorry, I don't understand how to set a context to the driver with doctrine mongodb

**Comment by alcaeus** [comment]
If you are just using doctrine/mongodb, you can pass options to the `Connection` class when creating it just like you would pass it to `MongoClient`:
```
$connection = new Doctrine\MongoDB\Connection($server, ['context' => ...]);
```

If you are using Doctrine ODM you'll have to pass a connection object (created like the one above) when creating your `DocumentManager` instance.
