### ISSUE TITLE
Use library GridFS implementation

### ISSUE THREAD

**Issue by alcaeus** [alcaeus/mongo-php-adapter#82]
Right now the adapter uses its own implementation of GridFS. Now that mongodb/mongo-php-library#57 has been merged, we could start using the GridFS implementation provided by mongo-php-library. This will have to wait for a 1.1.0 release in mongo-php-library.

**Comment by denji** [comment]
@alcaeus [Optional RocksDB and PerconaFT storage engines](https://www.percona.com/software/mongo-database/percona-server-for-mongodb)

**Comment by alcaeus** [comment]
Closing as per https://github.com/alcaeus/mongo-php-adapter/pull/220#issuecomment-482566021.
