### ISSUE TITLE
MongoCollection count() parameters error

### ISSUE THREAD

**Issue by shanghaiyangming** [alcaeus/mongo-php-adapter#83]

**Comment by shanghaiyangming** [comment]
old drivers:
public int MongoCollection::count ([ array $query = array() [, int $limit = 0 [, int $skip = 0 ]]] )
mongo-php-adapter:
public function count($query = [], array $options = [])

**Comment by alcaeus** [comment]
This will be fixed in 1.0.1 - thanks for the report!
