### ISSUE TITLE
MongoCursor hasNext iteration problem if nest find ，cursor will not iteration

### ISSUE THREAD

**Issue by shanghaiyangming** [alcaeus/mongo-php-adapter#86]
$datas = array();
        $cursor = $this->_collection->find($query, array(
            'hookLastResponseResult' => false
        ));
        $cursor->sort($sort);
        $cursor->skip($start)->limit($limit);
        while ($cursor->hasNext()) {
            $row = $cursor->getNext();
            if (! isset($row['isEditSafe'])) {
                $row['isEditSafe'] = true;
            }
            $row['locked'] = false;
            $lockInfo = $this->_lock->count(array(
                'project_id' => $this->_project_id,
                'collection_id' => myMongoId($row['_id']),
                'active' => true
            ));
            if ($lockInfo > 0) {
                $row['locked'] = true;
            }
            
            // 判断当前集合是否默认数据集合，如果是显示正确的集合
            if ($this->_plugin_data->isDefault(myMongoId($row['_id']))) {
                $row['defaultSourceData'] = true;
            } else {
                $row['defaultSourceData'] = false;
            }
            $row['indexNumber'] = $this->_index->getIndexNumber(myMongoId($row['_id']));
            
            $datas[] = $row;
        }
var_dump($datas);

**Comment by alcaeus** [comment]
Please provide a description of what you expect to happen and what actually happens. Ideally, provide a failing test case that passes on builds using `ext-mongo` but fails on those using the adapter. Just dumping a bunch of code in a ticket is not helpful, especially if it's not a standalone piece of code but relies on multiple external dependencies.
