### ISSUE TITLE
MongoCollection::distinct returns an empty array when an array of MongoId's are used in an $in statement

### ISSUE THREAD

**Issue by ccovey** [alcaeus/mongo-php-adapter#87]
With the following query I receive an empty array instead of a cursor like I expect.

```
$this->collection
       ->distinct(
           'sp',
           ['sl' => ['$in' => $sellerIds]]
      );
```
I know that data exists and should be returned via this query because I can change it to a find query and I get the 16 documents in a cursor like expected.

It seems to be something specific to passing MongoId's to the $in clause. I have distinct queries working where the array passed to $in is an array of strings instead of MongoId objects. Unfortunately  this is all the info I have currently. I don't see queries in the logs so can't see what it is actually running. Let me know what I can do to help track down the issue (Or where I am missing something simple.

**Comment by alcaeus** [comment]
Thanks for the report! This will be fixed in 1.0.1.

**Comment by ccovey** [comment]
ha that was quick thanks. Do you have a road map or timeline? I think we are probably around 1 month out from going live with the php 7 upgrade but this will be a blocker for sure so just trying to get an idea?

Again thanks!

**Comment by alcaeus** [comment]
No roadmap - releases are made whenever necessary/useful. That said, I've just tagged 1.0.1.
