### ISSUE TITLE
find([]) with error Method MongoDB::__toString() must return a string value

### ISSUE THREAD

**Issue by shanghaiyangming** [alcaeus/mongo-php-adapter#89]
<?php
include "vendor/autoload.php";

$client = new MongoClient('mongodb://127.0.0.1:27017');
$db = $client->selectDB('test');

$test1 = $client->selectCollection($db, 'test1');
$test2 = $client->selectCollection($db, 'test2');
$test1->drop();
$test2->drop();

for ($i = 0; $i < 5; $i ++) {
    $inertData = array(
        'a' => $i,
        'b' => time()
    );
    var_dump($test1->insert($inertData));
    $inertData1 = array(
        'a' => $i,
        'b' => time()
    );
    var_dump($test2->insert($inertData1));
}

$test1->findOne(array());//<--- is ok
$cursor = $test1->find(array());//<--- error 

error info:
PHP Catchable fatal error:  Method MongoDB::__toString() must return a string value in D:\MyCode\mongo-php-adapter-test\vendor\alcaeus\mongo-php-adapter\lib\Mongo\MongoCollection.php on line 91

**Comment by alcaeus** [comment]
Thanks!
