### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by srggroup** [alcaeus/mongo-php-adapter#92]
Hi!

My project used the Doctrine 2.2.2 version and now we are moveing to a new server, where the Mongo 3.2 is installed with the mongodb driver (1.1.5). I had to upgrade the Doctrine to 2.7, so I have to use this adapter now.

My site is extremely slow now, so I've tried to find the problem with the xdebug profiler. The first rows of the output (the numbers are in percentage):

<img width="1413" alt="profiler_output" src="https://cloud.githubusercontent.com/assets/548582/14320944/66a216e0-fc17-11e5-9473-807ef9dce4df.png">

Is it possible? Is there any solution for this problem?

**Comment by alcaeus** [comment]
I'm a bit confused by the version number for Doctrine - are you using DoctrineMongoDBBundle?

As for the high invocation count, I would assume the invocation count for the `toLegacy` method to be quite high. This method recursively walks over an array and converts any BSON types for the new driver to the old BSON types (e.g. `MongoDB\BSON\ObjectId` to `MongoId`). I haven't done any performance testing (yet) so I can't comment on the specifics, especially when seeing only a small portion of the data.

If you could provide a code sample along with some performance numbers for `ext-mongo` and the adapter I'd be happy to take a look.

**Comment by srggroup** [comment]
The main problem was the invocation count, it's true, and this is my fault. Finally I went back to Mongo 3.0 for these projects, because the code is too old, and not too optimal.
So the performance problem mainly caused by the wrong code :)
But thanks for the reaction :)
