### ISSUE TITLE
Can't call count on a cursor after a call to `iterator_to_array`has been made.

### ISSUE THREAD

**Issue by ccovey** [alcaeus/mongo-php-adapter#95]
I am not sure if this is actually an issue or something that you feel should be supported. I noticed this behavior when trying to update a test.

Here is an example of some code using Doctrine to be able to recreate

PaginatedCursor.php
```php
    class PaginatedCursor implements Paginatable
    {
        private $cursor;
        private $data;

        public function __construct(CursorInterface $cursor, $page = 1, $perPage = 20)
        {
            $this->cursor = $cursor;
            $this->page = $page > 0 ? $page : 1;
            $this->perPage = $perPage;
            $this->cursor
                ->skip($this->getOffset())
                ->limit($this->getLimit());
            $this->hasNextPage = $this->cursor->count(true) > $this->perPage;

            $this->data = new ArrayIterator(array_slice($this->cursor->toArray(), 0, $this->perPage));
        }

       public function count()
       {
           return $this->data->count();
       }
   }
```
    
    $cursor = $this->container->get('admin.sellable.repo')->createQueryBuilder()
            ->getQuery()
            ->execute();

    $paginatedCursor = new PaginatedCursor($cursor);
    $paginatedCursor->count(true); // returns valid count.
    dump($cursor->count(true));

The `$cursor->count(true)` call returns the following error.

`Cannot traverse an already closed generator`

So once a Generator has iterator_to_array called you can no longer call iterator_count on it. I know this is a language "issue" but wasn't sure if this was something you intended to support with the adapter. I don't think this is something that many will actually do in the wild.

**Comment by alcaeus** [comment]
Thanks for the report! This should be fixed with #96 - could you test that version please?
