### ISSUE TITLE
Query returns only id not the fields specified.

### ISSUE THREAD

**Issue by alcaeus** [alcaeus/mongo-php-adapter#97]
Previously reported by @ccovey in mongodb/mongo-php-driver#294.

**Comment by coudenysj** [comment]
Was this bug reintroduced in a newer version?

I'm currently using 1.0.7 and the field selection is only returning the _id.

**Comment by coudenysj** [comment]
I think the fix from d851097 should be used in the `\MongoCollection::find()` method too.

**Comment by alcaeus** [comment]
Could you test the current 1.0.x branch? I made some changes to projection in #145 which would be released as 1.0.8 in the near future.
